title: Belkirk College of Engineering
short_title: Belkirk
description: Jekyll demo for Forestry CMS
baseurl: /test
permalink: '/:path/'
defaults:
  - scope:
      path: ''
    values:
      layout: page
  - scope:
      path: ''
      type: posts
    values:
      layout: post
collections:
  people:
    output: true
    permalink: '/about/:path/'
  posts:
    output: true
  projects:
    output: true
    permalink: '/projects/:path/'
jekyll-archives:
  enabled: all
  layout: archive
plugins:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
